/*
  Звёздный Старатель — Фаза 3.
  Главное: весь баланс в CONFIG, SDK Яндекс Игр через js/sdk.js, graceful fallback.
*/
(function () {
  'use strict';

  const CONFIG = {
    save: { version: 3, key: 'star_miner_save_v3', oldKeys: ['star_miner_save_v2', 'star_miner_save_v1'], autosaveMs: 15000 },
    yandex: { leaderboardName: 'star_dust', fullscreenCooldownMs: 4 * 60 * 1000 },
    remoteFlags: { oreMultiplier: '1', tapMultiplier: '1', prestigeUnlockOre: '50000', rewardedCrystalAmount: '12' },
    start: { ore: 0, crystals: 15, starDust: 0, drones: 1 },
    mining: { baseTap: 1, baseDronePerSec: 0.25, critChancePerLevel: 0.015, critMultiplier: 6 },
    economy: { costGrowth: 1.17, discountPerLevel: 0.018, minCostFactor: 0.35 },
    prestige: { unlockOre: 50000, baseDustGain: 8, orePower: 0.5, dustBonus: 0.04, scannerBonus: 0.03, rewardedDustBonus: 0.5 },
    offline: { capSeconds: 8 * 60 * 60, incomeFactor: 0.65, minSecondsToShow: 60 },
    ads: { incomeBoostSeconds: 4 * 60 * 60, freeCrystalsDaily: 12 },
    daily: [{ ore: 120, crystals: 1 }, { ore: 450, crystals: 1 }, { ore: 1200, crystals: 2 }, { ore: 3000, crystals: 2 }, { ore: 7500, crystals: 3 }, { ore: 16000, crystals: 4 }, { ore: 35000, crystals: 6 }],
    iap: {
      noads: { id: 'noads', type: 'permanent' }, starter_pack: { id: 'starter_pack', type: 'consumable', crystals: 120, ore: 25000 },
      crystals_small: { id: 'crystals_small', type: 'consumable', crystals: 80 }, crystals_big: { id: 'crystals_big', type: 'consumable', crystals: 450 },
      drill_skin_neon: { id: 'drill_skin_neon', type: 'permanent', skin: 'neon' }
    },
    upgrades: [
      { id: 'tap', n: ['Усилитель бура', 'Drill Booster'], d: ['+1 руда за тап', '+1 ore per tap'], max: 200, cost: 15, g: 1.16, tap: 1, icon: 'icon_upgrade' },
      { id: 'drones', n: ['Новые дроны', 'More Drones'], d: ['+1 добывающий дрон', '+1 mining drone'], max: 120, cost: 60, g: 1.18, drones: 1, icon: 'drone_basic' },
      { id: 'dronePower', n: ['Лазерные резцы', 'Laser Cutters'], d: ['+0.18 руды/сек к дрону', '+0.18 ore/sec per drone'], max: 160, cost: 95, g: 1.17, dronePower: 0.18, icon: 'effect_spark' },
      { id: 'droneSpeed', n: ['Разгон двигателей', 'Engine Tuning'], d: ['+6% скорости дронов', '+6% drone speed'], max: 120, cost: 180, g: 1.18, speed: 0.06, icon: 'effect_tap_burst' },
      { id: 'mult', n: ['Рудный анализатор', 'Ore Analyzer'], d: ['+8% ко всей добыче', '+8% all income'], max: 100, cost: 550, g: 1.22, global: 0.08, icon: 'currency_ore' },
      { id: 'crit', n: ['Критические трещины', 'Critical Cracks'], d: ['+1.5% шанс крит. тапа', '+1.5% critical tap chance'], max: 50, cost: 1300, g: 1.24, icon: 'effect_spark' },
      { id: 'discount', n: ['Торговый модуль', 'Trade Module'], d: ['Снижает цены апгрейдов', 'Lowers prices'], max: 50, cost: 2600, g: 1.25, icon: 'icon_shop' },
      { id: 'offline', n: ['Ночная смена', 'Night Shift'], d: ['+4% к оффлайн-доходу', '+4% offline income'], max: 40, cost: 6000, g: 1.28, offline: 0.04, icon: 'icon_daily' },
      { id: 'scanner', n: ['Сканер галактик', 'Galaxy Scanner'], d: ['+3% пыли при прыжке', '+3% dust on jump'], max: 60, cost: 15000, g: 1.30, icon: 'icon_prestige' },
      { id: 'crystal', n: ['Кристальный фильтр', 'Crystal Filter'], d: ['Кристаллы за крупную добычу', 'Crystals from income'], max: 25, cost: 50000, g: 1.34, icon: 'currency_crystal' }
    ],
    achievements: [
      { id: 'tap1', n: ['Первый удар', 'First Strike'], d: ['Тапните астероид', 'Tap the asteroid'], v: 'taps', t: 1, c: 1 },
      { id: 'ore1k', n: ['Тысяча руды', 'One Thousand Ore'], d: ['Добудьте 1K руды всего', 'Mine 1K total ore'], v: 'totalOre', t: 1000, c: 2 },
      { id: 'ore1m', n: ['Миллионер', 'Millionaire'], d: ['Добудьте 1M руды всего', 'Mine 1M total ore'], v: 'totalOre', t: 1000000, c: 5 },
      { id: 'drones5', n: ['Рой помощников', 'Helper Swarm'], d: ['Получите 5 дронов', 'Own 5 drones'], v: 'drones', t: 5, c: 2 },
      { id: 'up20', n: ['Инженер', 'Engineer'], d: ['Купите 20 уровней апгрейдов', 'Buy 20 upgrade levels'], v: 'upgradeLevels', t: 20, c: 3 },
      { id: 'prestige1', n: ['Новая галактика', 'New Galaxy'], d: ['Сделайте первый прыжок', 'Make the first jump'], v: 'prestiges', t: 1, c: 6 },
      { id: 'dust100', n: ['Звёздный след', 'Star Trail'], d: ['Накопите 100 пыли', 'Collect 100 dust'], v: 'starDust', t: 100, c: 8 },
      { id: 'daily3', n: ['Возвращение', 'Comeback'], d: ['Заберите ежедневку 3 дня', 'Claim 3 days'], v: 'dailyStreak', t: 3, c: 3 }
    ]
  };

  const L = { ru: { ore: 'Руда', crystals: 'Кристаллы', dust: 'Пыль', shop: 'Апгрейды', jump: 'Прыжок', daily: 'Ежедневно', leaders: 'Лидеры', settings: 'Настройки', ach: 'Достижения', store: 'Бонусы и покупки', buy: 'Купить', collect: 'Забрать', max: 'Макс.', noOre: 'Не хватает руды', tap: 'Тапайте астероид', need: 'Нужно больше руды', offline: 'Дроны добыли без вас:', adFail: 'Реклама недоступна', incomeAd: '×2 доход на 4 часа', dustAd: '+50% пыли за рекламу', dustReady: '+50% к прыжку готово', freeCrystals: 'Бесплатные кристаллы', cloud: 'Облачное сохранение', guest: 'Гость: localStorage', local: 'SDK недоступен', noads: 'Реклама отключена', banner: 'Sticky-баннер', sound: 'Звук', on: 'вкл', off: 'выкл', reset: 'Сбросить прогресс', emptyLb: 'Лидерборд пока недоступен', purchaseOk: 'Покупка начислена', purchaseFail: 'Покупка не завершена', already: 'Уже получено сегодня' }, en: { ore: 'Ore', crystals: 'Crystals', dust: 'Dust', shop: 'Upgrades', jump: 'Jump', daily: 'Daily', leaders: 'Leaders', settings: 'Settings', ach: 'Achievements', store: 'Boosts & purchases', buy: 'Buy', collect: 'Collect', max: 'Max', noOre: 'Not enough ore', tap: 'Tap asteroid', need: 'Need more ore', offline: 'Drones mined away:', adFail: 'Ad unavailable', incomeAd: '×2 income for 4 hours', dustAd: '+50% dust for ad', dustReady: '+50% jump ready', freeCrystals: 'Free crystals', cloud: 'Cloud save', guest: 'Guest: localStorage', local: 'SDK unavailable', noads: 'Ads removed', banner: 'Sticky banner', sound: 'Sound', on: 'on', off: 'off', reset: 'Reset progress', emptyLb: 'Leaderboard unavailable', purchaseOk: 'Purchase granted', purchaseFail: 'Purchase failed', already: 'Already claimed today' } };

  const canvas = document.getElementById('gameCanvas'), ctx = canvas.getContext('2d'), SDK = window.StarMinerSDK;
  let a = window.StarMinerProceduralAssets ? window.StarMinerProceduralAssets.createAssets().sprites : {}, lang = 'ru', W = 1, H = 1, DPR = 1, state, ui = [], modal = 'loading', scroll = 0, drag = null, offline = null, lb = [], catalog = {}, toast = [], floats = [], last = performance.now(), auto = performance.now(), pulse = 0, paused = false, status = '';
  const t = k => (L[lang] && L[lang][k]) || L.ru[k] || k, n = arr => arr[lang === 'ru' ? 0 : 1], day = () => new Date().toISOString().slice(0, 10);

  function fresh() { const u = {}; CONFIG.upgrades.forEach(x => u[x.id] = 0); return { version: CONFIG.save.version, ore: CONFIG.start.ore, crystals: CONFIG.start.crystals, starDust: CONFIG.start.starDust, totalOre: 0, galaxyOre: 0, taps: 0, prestiges: 0, upgradeLevels: 0, upgrades: u, achievements: {}, daily: { streak: 0, lastDate: '', pending: false }, boosts: { incomeUntil: 0, dustAdReady: false }, purchases: { noads: false, skins: {} }, ads: { crystalDate: '' }, settings: { sound: false, banner: true }, selectedSkin: 'basic', reviewAsked: false, lastSaveTime: Date.now() }; }
  function migrate(x) { const f = fresh(); if (!x) return f; return { ...f, ...x, upgrades: { ...f.upgrades, ...(x.upgrades || {}) }, achievements: { ...f.achievements, ...(x.achievements || {}) }, daily: { ...f.daily, ...(x.daily || {}) }, boosts: { ...f.boosts, ...(x.boosts || {}) }, purchases: { ...f.purchases, ...(x.purchases || {}), skins: { ...f.purchases.skins, ...((x.purchases || {}).skins || {}) } }, ads: { ...f.ads, ...(x.ads || {}) }, settings: { ...f.settings, ...(x.settings || {}) }, version: CONFIG.save.version }; }
  async function load() { let x = SDK ? await SDK.loadSave(CONFIG.save.key, migrate) : null; if (!x && SDK) for (const k of CONFIG.save.oldKeys) { const o = SDK.readLocal(k); if (o) { x = o; break; } } state = migrate(x); }
  function save(flush) { if (!state || !SDK) return; state.lastSaveTime = Date.now(); SDK.save(CONFIG.save.key, state, { starDust: Math.floor(state.starDust), totalOre: Math.floor(state.totalOre), crystals: Math.floor(state.crystals), prestiges: state.prestiges }, !!flush); }
  function flags(f) { f = f || {}; const om = +f.oreMultiplier, tm = +f.tapMultiplier, po = +f.prestigeUnlockOre, rc = +f.rewardedCrystalAmount; if (om > 0) CONFIG.mining.baseDronePerSec *= om; if (tm > 0) CONFIG.mining.baseTap *= tm; if (po > 1000) CONFIG.prestige.unlockOre = po; if (rc > 0) CONFIG.ads.freeCrystalsDaily = rc; }

  function fmt(x) { const u = ['', 'K', 'M', 'B', 'T', 'Qa', 'Qi']; let i = 0; while (Math.abs(x) >= 1000 && i < u.length - 1) { x /= 1000; i++; } return (i ? x.toFixed(x < 10 ? 2 : x < 100 ? 1 : 0) : Math.floor(x)).replace(/\.0$/, '') + u[i]; }
  function lvl(id) { return state.upgrades[id] || 0; } function up(id) { return CONFIG.upgrades.find(x => x.id === id); }
  function discount() { return Math.max(CONFIG.economy.minCostFactor, 1 - lvl('discount') * CONFIG.economy.discountPerLevel); }
  function cost(u) { return Math.floor(u.cost * Math.pow(u.g || CONFIG.economy.costGrowth, lvl(u.id)) * discount()); }
  function boost() { return Date.now() < state.boosts.incomeUntil ? 2 : 1; }
  function drones() { return CONFIG.start.drones + lvl('drones'); }
  function mult() { return (1 + state.starDust * CONFIG.prestige.dustBonus + lvl('mult') * up('mult').global) * boost(); }
  function tapPower() { return (CONFIG.mining.baseTap + lvl('tap') * up('tap').tap) * mult(); }
  function dps() { return drones() * (CONFIG.mining.baseDronePerSec + lvl('dronePower') * up('dronePower').dronePower) * (1 + lvl('droneSpeed') * up('droneSpeed').speed) * mult(); }
  function offlineDps() { return dps() * CONFIG.offline.incomeFactor * (1 + lvl('offline') * up('offline').offline); }
  function dustBase() { if (state.galaxyOre < CONFIG.prestige.unlockOre) return 0; return Math.max(1, Math.floor(Math.pow(state.galaxyOre / CONFIG.prestige.unlockOre, CONFIG.prestige.orePower) * CONFIG.prestige.baseDustGain * (1 + lvl('scanner') * CONFIG.prestige.scannerBonus))); }
  function dustGain() { const b = dustBase(); return state.boosts.dustAdReady ? Math.floor(b * (1 + CONFIG.prestige.rewardedDustBonus)) : b; }
  function addOre(x) { if (x <= 0) return; state.ore += x; state.totalOre += x; state.galaxyOre += x; }
  function buy(id) { const u = up(id), c = cost(u); if (lvl(id) >= u.max) return say(t('max')); if (state.ore < c) return say(t('noOre')); state.ore -= c; state.upgrades[id]++; state.upgradeLevels++; pop('UP!', W / 2, H / 2, '#6ceb49'); checkAch(); save(false); }
  function mine(x, y) { let v = tapPower(); if (Math.random() < lvl('crit') * CONFIG.mining.critChancePerLevel) v *= CONFIG.mining.critMultiplier; addOre(v); state.taps++; pulse = 1; pop('+' + fmt(v), x, y - 30, '#2bd8ff'); checkAch(); }
  function jump() { const g = dustGain(); if (!g) return say(t('need')); save(true); state.starDust += g; state.prestiges++; state.ore = 0; state.galaxyOre = 0; CONFIG.upgrades.forEach(u => state.upgrades[u.id] = 0); state.boosts.dustAdReady = false; modal = null; say('+' + fmt(g) + ' ' + t('dust')); checkAch(); save(true); if (SDK) { SDK.submitLeaderboard(CONFIG.yandex.leaderboardName, state.starDust, 'Prestige ' + state.prestiges); if (!state.reviewAsked && state.prestiges >= 3) { state.reviewAsked = true; SDK.requestReview(); } if (!state.purchases.noads) SDK.showFullscreen({ cooldownMs: CONFIG.yandex.fullscreenCooldownMs, noAds: state.purchases.noads }); } }
  function checkAch() { CONFIG.achievements.forEach(x => { if (state.achievements[x.id]) return; let v = x.v === 'drones' ? drones() : x.v === 'dailyStreak' ? state.daily.streak : state[x.v]; if (v >= x.t) { state.achievements[x.id] = true; state.crystals += x.c; say(t('ach') + ': +' + x.c); } }); }
  function daily() { if (!state.daily.pending) return say(t('already')); const r = CONFIG.daily[Math.min(state.daily.streak, CONFIG.daily.length - 1)]; addOre(r.ore); state.crystals += r.crystals; state.daily.streak++; state.daily.lastDate = day(); state.daily.pending = false; modal = null; say('+' + fmt(r.ore) + ', +' + r.crystals); save(true); }
  function calcOffline() { const s = Math.floor((Date.now() - (state.lastSaveTime || Date.now())) / 1000); if (s >= CONFIG.offline.minSecondsToShow) { const c = Math.min(s, CONFIG.offline.capSeconds), g = offlineDps() * c; if (g > 1) { offline = { sec: c, gain: g }; modal = 'offline'; } } }
  function claimOffline(k) { if (!offline) return; addOre(offline.gain * k); say('+' + fmt(offline.gain * k)); offline = null; modal = null; save(true); }
  function reward(kind) { if (!SDK) return say(t('adFail')); paused = true; save(true); const ok = SDK.showRewarded(() => { if (kind === 'income') { state.boosts.incomeUntil = Math.max(Date.now(), state.boosts.incomeUntil || 0) + CONFIG.ads.incomeBoostSeconds * 1000; say(t('incomeAd')); } if (kind === 'offline') claimOffline(2); if (kind === 'dust') { state.boosts.dustAdReady = true; say(t('dustReady')); } if (kind === 'crystals') { state.crystals += CONFIG.ads.freeCrystalsDaily; state.ads.crystalDate = day(); say('+' + CONFIG.ads.freeCrystalsDaily + ' ' + t('crystals')); } save(true); }, () => { paused = false; }, () => { paused = false; say(t('adFail')); }); if (!ok) { paused = false; say(t('adFail')); } }
  async function initPurchases() { if (!SDK) return; (SDK.state.catalog || []).forEach(p => catalog[p.id] = p); const ps = await SDK.refreshPurchases(); for (const p of ps) grant(p, CONFIG.iap[p.productID] && CONFIG.iap[p.productID].type === 'consumable'); await SDK.syncBanner(state.settings.banner, state.purchases.noads); }
  function grant(p, consume) { const id = p && (p.productID || p.id), item = CONFIG.iap[id]; if (!item) return; if (id === 'noads') { state.purchases.noads = true; SDK.syncBanner(false, true); } if (item.skin) { state.purchases.skins[item.skin] = true; state.selectedSkin = item.skin; } if (item.crystals) state.crystals += item.crystals; if (item.ore) addOre(item.ore); say(t('purchaseOk')); save(true); if (consume && p.purchaseToken) SDK.consumePurchase(p.purchaseToken); }
  async function buyProduct(id) { if (!SDK || !SDK.state.paymentsAvailable) return say(t('purchaseFail')); paused = true; SDK.gameplayStop(); try { grant(await SDK.purchase(id), CONFIG.iap[id].type === 'consumable'); } catch (_) { say(t('purchaseFail')); } paused = false; SDK.gameplayStart(); }
  async function showLb() { modal = 'leader'; lb = SDK ? await SDK.getLeaderboard(CONFIG.yandex.leaderboardName) : []; }

  function r(x, y, w, h, rad = 14) { ctx.beginPath(); ctx.moveTo(x + rad, y); ctx.arcTo(x + w, y, x + w, y + h, rad); ctx.arcTo(x + w, y + h, x, y + h, rad); ctx.arcTo(x, y + h, x, y, rad); ctx.arcTo(x, y, x + w, y, rad); ctx.closePath(); }
  function txt(s, x, y, size, col = '#fff', align = 'left') { ctx.font = '800 ' + size + 'px Arial'; ctx.textAlign = align; ctx.textBaseline = 'middle'; ctx.fillStyle = col; ctx.fillText(s, x, y); }
  function button(id, x, y, w, h, label, fn, color) { r(x, y, w, h, 16); ctx.fillStyle = color || 'rgba(32,158,228,.85)'; ctx.fill(); ctx.strokeStyle = 'rgba(255,255,255,.25)'; ctx.stroke(); txt(label, x + w / 2, y + h / 2, Math.min(16, h * .42), '#fff', 'center'); ui.push({ id, x, y, w, h, fn }); }
  function say(s) { toast.push({ s, life: 2.3 }); if (toast.length > 4) toast.shift(); }
  function pop(s, x, y, c) { floats.push({ s, x, y, c, life: .8 }); }
  function resize() { DPR = Math.min(2, devicePixelRatio || 1); W = Math.max(320, innerWidth); H = Math.max(480, innerHeight); canvas.width = W * DPR; canvas.height = H * DPR; canvas.style.width = W + 'px'; canvas.style.height = H + 'px'; ctx.setTransform(DPR, 0, 0, DPR, 0, 0); }
  function bg(time) { const b = a.background_space; if (b) { const s = Math.max(W / b.width, H / b.height); ctx.drawImage(b, (W - b.width * s) / 2, (H - b.height * s) / 2, b.width * s, b.height * s); } else { ctx.fillStyle = '#05081c'; ctx.fillRect(0, 0, W, H); } ctx.fillStyle = 'rgba(0,0,0,.35)'; ctx.fillRect(0, 0, W, H); }
  function top() { r(12, 12, W - 24, 82, 20); ctx.fillStyle = 'rgba(10,19,54,.9)'; ctx.fill(); cur(22, 52, 'currency_ore', t('ore'), state.ore); cur(W * .36, 52, 'currency_crystal', t('crystals'), state.crystals); cur(W * .68, 52, 'currency_dust', t('dust'), state.starDust); txt(fmt(dps()) + '/sec' + (boost() > 1 ? ' x2' : ''), W - 24, 88, 13, '#6ceb49', 'right'); }
  function cur(x, y, icon, label, val) { if (a[icon]) ctx.drawImage(a[icon], x, y - 22, 40, 40); txt(label, x + 46, y - 10, 11, '#9fb0dc'); txt(fmt(val), x + 46, y + 12, 18); }
  function scene(time) { const cx = W / 2, cy = 112 + (H - 240) * .43, rad = Math.max(86, Math.min(160, Math.min(W, H) * .22)); const spr = a[state.galaxyOre > CONFIG.prestige.unlockOre * 1.25 ? 'asteroid_gold' : state.galaxyOre > CONFIG.prestige.unlockOre * .4 ? 'asteroid_crystal' : 'asteroid_normal']; const drone = a[state.selectedSkin === 'neon' ? 'drone_plasma' : 'drone_basic']; for (let i = 0; i < Math.min(drones(), 8) && drone; i++) { const ang = i * 6.283 / Math.min(drones(), 8) + time * .00045, x = cx + Math.cos(ang) * rad * 1.4, y = cy + Math.sin(ang) * rad * .72; ctx.drawImage(drone, x - 34, y - 22, 68, 44); } if (spr) ctx.drawImage(spr, cx - rad * (1 + pulse * .05), cy - rad * (1 + pulse * .05), rad * 2 * (1 + pulse * .05), rad * 2 * (1 + pulse * .05)); const bw = Math.min(520, W * .75), x = (W - bw) / 2, y = cy + rad + 35, q = Math.min(1, state.galaxyOre / CONFIG.prestige.unlockOre); r(x, y, bw, 24, 12); ctx.fillStyle = '#07102e'; ctx.fill(); r(x + 3, y + 3, (bw - 6) * q, 18, 10); ctx.fillStyle = '#2bd8ff'; ctx.fill(); txt(fmt(state.galaxyOre) + '/' + fmt(CONFIG.prestige.unlockOre), W / 2, y + 12, 12, '#fff', 'center'); txt(t('tap'), W / 2, y + 58, 18, '#9fb0dc', 'center'); ui.push({ id: 'asteroid', x: cx - rad, y: cy - rad, w: rad * 2, h: rad * 2, fn: p => mine(p.x, p.y) }); pulse = Math.max(0, pulse - .08); }
  function bottom() { const y = H - 110, names = [[t('shop'), 'icon_upgrade', () => open('shop')], [t('jump'), 'icon_prestige', () => open('jump')], [t('daily'), 'icon_daily', () => open('daily')], [t('leaders'), 'icon_leaderboard', showLb], [t('settings'), 'icon_settings', () => open('settings')]], gap = 6, bw = (W - 38 - gap * 4) / 5; r(10, y, W - 20, 100, 22); ctx.fillStyle = 'rgba(6,12,37,.88)'; ctx.fill(); names.forEach((it, i) => { const x = 19 + i * (bw + gap); r(x, y + 12, bw, 76, 16); ctx.fillStyle = it[0] === t('jump') && dustGain() ? 'rgba(255,185,35,.35)' : 'rgba(28,42,92,.9)'; ctx.fill(); if (a[it[1]]) ctx.drawImage(a[it[1]], x + bw / 2 - 18, y + 20, 36, 36); txt(it[0], x + bw / 2, y + 74, bw < 70 ? 10 : 12, '#fff', 'center'); ui.push({ x, y: y + 12, w: bw, h: 76, fn: it[2] }); }); }
  function open(m) { modal = m; scroll = 0; }
  function box() { const w = Math.min(760, W - 24), h = Math.min(H - 56, 620); return { x: (W - w) / 2, y: (H - h) / 2, w, h }; }
  function modalDraw() { if (!modal) return; ctx.fillStyle = 'rgba(0,0,0,.58)'; ctx.fillRect(0, 0, W, H); const b = box(); r(b.x, b.y, b.w, b.h, 24); ctx.fillStyle = 'rgba(27,40,92,.96)'; ctx.fill(); button('close', b.x + b.w - 78, b.y + 14, 58, 38, '×', () => modal = null); const title = { shop: t('shop'), jump: t('jump'), daily: t('daily'), settings: t('settings'), ach: t('ach'), store: t('store'), leader: t('leaders'), offline: 'Offline', loading: 'Loading' }[modal] || ''; txt(title, b.x + 24, b.y + 34, 24); if (modal === 'shop') shop(b); if (modal === 'jump') jumpWin(b); if (modal === 'daily') dailyWin(b); if (modal === 'offline') offWin(b); if (modal === 'settings') settings(b); if (modal === 'ach') ach(b); if (modal === 'store') store(b); if (modal === 'leader') leaders(b); }
  function shop(b) { let y = b.y + 76 - scroll; CONFIG.upgrades.forEach(u => { if (y > b.y + 60 && y < b.y + b.h - 20) { r(b.x + 18, y, b.w - 36, 68, 16); ctx.fillStyle = 'rgba(12,24,61,.88)'; ctx.fill(); if (a[u.icon]) ctx.drawImage(a[u.icon], b.x + 28, y + 10, 48, 48); txt(n(u.n), b.x + 86, y + 18, 16); txt(n(u.d), b.x + 86, y + 40, 12, '#9fb0dc'); txt('Lv ' + lvl(u.id) + '/' + u.max, b.x + 86, y + 58, 12, '#ffb923'); button('buy', b.x + b.w - 140, y + 14, 112, 42, lvl(u.id) >= u.max ? t('max') : fmt(cost(u)), () => buy(u.id), state.ore >= cost(u) ? 'rgba(76,189,44,.95)' : 'rgba(70,80,120,.8)'); } y += 78; }); }
  function jumpWin(b) { const g = dustGain(), base = dustBase(), cx = b.x + b.w / 2; if (a.currency_dust) ctx.drawImage(a.currency_dust, cx - 54, b.y + 78, 108, 108); txt(g ? '+' + fmt(g) + ' ' + t('dust') : t('need'), cx, b.y + 220, 26, g ? '#ffb923' : '#9fb0dc', 'center'); txt(fmt(state.galaxyOre) + ' / ' + fmt(CONFIG.prestige.unlockOre), cx, b.y + 260, 16, '#9fb0dc', 'center'); button('dustad', b.x + 44, b.y + b.h - 150, b.w - 88, 48, state.boosts.dustAdReady ? t('dustReady') : t('dustAd') + (base ? ' +' + fmt(base * .5) : ''), () => state.boosts.dustAdReady ? say(t('dustReady')) : reward('dust'), 'rgba(32,158,228,.9)'); button('jump', b.x + 44, b.y + b.h - 86, b.w - 88, 56, t('jump'), jump, g ? 'rgba(244,142,32,.95)' : 'rgba(70,80,120,.8)'); }
  function dailyWin(b) { const rwd = CONFIG.daily[Math.min(state.daily.streak, CONFIG.daily.length - 1)], cx = b.x + b.w / 2; if (a.icon_daily) ctx.drawImage(a.icon_daily, cx - 56, b.y + 88, 112, 112); txt('Day ' + Math.min(state.daily.streak + 1, 7), cx, b.y + 230, 30, '#ffb923', 'center'); txt('+' + fmt(rwd.ore) + ' ' + t('ore'), cx, b.y + 275, 22, '#fff', 'center'); txt('+' + rwd.crystals + ' ' + t('crystals'), cx, b.y + 310, 20, '#2bd8ff', 'center'); button('daily', b.x + 44, b.y + b.h - 86, b.w - 88, 56, state.daily.pending ? t('collect') : t('already'), daily, 'rgba(76,189,44,.95)'); }
  function offWin(b) { const cx = b.x + b.w / 2; txt(t('offline'), cx, b.y + 150, 20, '#9fb0dc', 'center'); txt('+' + fmt(offline ? offline.gain : 0) + ' ' + t('ore'), cx, b.y + 205, 34, '#2bd8ff', 'center'); button('collect', b.x + 44, b.y + b.h - 86, (b.w - 104) / 2, 56, t('collect'), () => claimOffline(1), 'rgba(76,189,44,.95)'); button('x2', b.x + 60 + (b.w - 104) / 2, b.y + b.h - 86, (b.w - 104) / 2, 56, '×2 AD', () => reward('offline'), 'rgba(244,142,32,.95)'); }
  function settings(b) { let y = b.y + 94; txt(status, b.x + 34, y, 15, '#9fb0dc'); y += 52; button('sound', b.x + 34, y, b.w - 68, 46, t('sound') + ': ' + (state.settings.sound ? t('on') : t('off')), () => { state.settings.sound = !state.settings.sound; save(true); }); y += 58; button('banner', b.x + 34, y, b.w - 68, 46, state.purchases.noads ? t('noads') : t('banner') + ': ' + (state.settings.banner ? t('on') : t('off')), () => { state.settings.banner = !state.settings.banner; if (SDK) SDK.syncBanner(state.settings.banner, state.purchases.noads); save(true); }); y += 58; button('store', b.x + 34, y, b.w - 68, 46, t('store'), () => open('store'), 'rgba(244,142,32,.95)'); y += 58; button('ach', b.x + 34, y, b.w - 68, 46, t('ach'), () => open('ach')); y += 58; button('reset', b.x + 34, y, b.w - 68, 46, t('reset'), () => { localStorage.removeItem(CONFIG.save.key); state = fresh(); modal = null; save(true); }, 'rgba(255,88,106,.95)'); }
  function ach(b) { let y = b.y + 80 - scroll; CONFIG.achievements.forEach(x => { if (y > b.y + 60 && y < b.y + b.h - 20) { const done = state.achievements[x.id], val = x.v === 'drones' ? drones() : x.v === 'dailyStreak' ? state.daily.streak : state[x.v]; r(b.x + 20, y, b.w - 40, 62, 16); ctx.fillStyle = done ? 'rgba(61,90,44,.82)' : 'rgba(12,24,61,.88)'; ctx.fill(); txt(n(x.n), b.x + 36, y + 18, 16); txt(n(x.d), b.x + 36, y + 42, 12, '#9fb0dc'); txt(done ? '✓ +' + x.c : fmt(Math.min(val, x.t)) + '/' + fmt(x.t), b.x + b.w - 34, y + 31, 14, done ? '#6ceb49' : '#ffb923', 'right'); } y += 72; }); }
  function store(b) { const rows = [['income', t('incomeAd'), 'AD', () => reward('income')], ['crystal', t('freeCrystals'), 'AD', () => state.ads.crystalDate === day() ? say(t('already')) : reward('crystals')], ['noads', 'No Ads', price('noads'), () => buyProduct('noads')], ['starter_pack', 'Starter Pack', price('starter_pack'), () => buyProduct('starter_pack')], ['crystals_small', 'Crystals Small', price('crystals_small'), () => buyProduct('crystals_small')], ['crystals_big', 'Crystals Big', price('crystals_big'), () => buyProduct('crystals_big')], ['drill_skin_neon', 'Neon Drill Skin', price('drill_skin_neon'), () => buyProduct('drill_skin_neon')]]; let y = b.y + 80 - scroll; rows.forEach(row => { if (y > b.y + 60 && y < b.y + b.h - 20) { r(b.x + 20, y, b.w - 40, 60, 16); ctx.fillStyle = 'rgba(12,24,61,.88)'; ctx.fill(); txt(row[1], b.x + 38, y + 22, 16); txt(row[2], b.x + 38, y + 44, 12, '#9fb0dc'); button('p', b.x + b.w - 138, y + 12, 100, 38, row[2] === 'AD' ? 'AD' : t('buy'), row[3], row[2] === 'AD' ? 'rgba(244,142,32,.95)' : 'rgba(76,189,44,.95)'); } y += 70; }); }
  function price(id) { return catalog[id] && catalog[id].price ? catalog[id].price : (SDK && SDK.state.paymentsAvailable ? '—' : 'SDK off'); }
  function leaders(b) { if (!lb.length) txt(t('emptyLb'), b.x + b.w / 2, b.y + 170, 20, '#9fb0dc', 'center'); lb.slice(0, 10).forEach((x, i) => { const y = b.y + 90 + i * 38; txt('#' + (x.rank + 1), b.x + 36, y, 16, '#ffb923'); txt(x.name || 'Player', b.x + 96, y, 16); txt(fmt(x.score), b.x + b.w - 38, y, 16, '#2bd8ff', 'right'); }); button('refresh', b.x + 44, b.y + b.h - 76, b.w - 88, 48, 'Refresh', showLb); }

  function frame(tm) { const dt = Math.min(.1, (tm - last) / 1000); last = tm; ui = []; if (state && !paused) addOre(dps() * dt); ctx.clearRect(0, 0, W, H); bg(tm); if (state) { top(); scene(tm); bottom(); } floats = floats.filter(f => { f.life -= dt; f.y -= 30 * dt; ctx.globalAlpha = Math.max(0, f.life / .8); txt(f.s, f.x, f.y, 22, f.c, 'center'); ctx.globalAlpha = 1; return f.life > 0; }); toast = toast.filter((o, i) => { o.life -= dt; r(W / 2 - 190, 112 + i * 40, 380, 32, 16); ctx.fillStyle = 'rgba(6,12,37,.88)'; ctx.fill(); txt(o.s, W / 2, 128 + i * 40, 14, '#fff', 'center'); return o.life > 0; }); modalDraw(); if (state && tm - auto > CONFIG.save.autosaveMs) { save(false); auto = tm; } requestAnimationFrame(frame); }
  function pos(e) { const q = canvas.getBoundingClientRect(); return { x: e.clientX - q.left, y: e.clientY - q.top }; }
  function click(p) { for (let i = ui.length - 1; i >= 0; i--) { const b = ui[i]; if (p.x >= b.x && p.x <= b.x + b.w && p.y >= b.y && p.y <= b.y + b.h) return b.fn(p); } }
  canvas.addEventListener('pointerdown', e => { e.preventDefault(); const p = pos(e); drag = { y: p.y, last: p.y, moved: false }; });
  canvas.addEventListener('pointermove', e => { if (!drag) return; const p = pos(e), dy = p.y - drag.last; if (Math.abs(p.y - drag.y) > 8) drag.moved = true; if (drag.moved && ['shop', 'ach', 'store'].includes(modal)) scroll = Math.max(0, scroll - dy); drag.last = p.y; });
  canvas.addEventListener('pointerup', e => { e.preventDefault(); const p = pos(e), moved = drag && drag.moved; drag = null; if (!moved) click(p); });
  canvas.addEventListener('wheel', e => { if (['shop', 'ach', 'store'].includes(modal)) { e.preventDefault(); scroll = Math.max(0, scroll + e.deltaY); } }, { passive: false });
  addEventListener('resize', resize); addEventListener('beforeunload', () => save(true)); document.addEventListener('visibilitychange', () => { if (document.hidden) { save(true); SDK && SDK.gameplayStop(); } else { SDK && SDK.gameplayStart(); } });

  async function boot() { resize(); requestAnimationFrame(frame); if (SDK) { await SDK.init(CONFIG.remoteFlags); lang = ((SDK.state.lang || 'ru').slice(0, 2) === 'ru') ? 'ru' : 'en'; flags(SDK.state.flags); } await load(); status = !SDK || !SDK.state.sdkAvailable ? t('local') : (SDK.state.authorized ? t('cloud') : t('guest')); await initPurchases(); if (state.daily.lastDate !== day()) { state.daily.pending = true; modal = 'daily'; } calcOffline(); checkAch(); SDK && SDK.loadingReady(); SDK && SDK.gameplayStart(); SDK && SDK.submitLeaderboard(CONFIG.yandex.leaderboardName, state.starDust, 'Prestige ' + state.prestiges); say(status); save(false); if (modal === 'loading') modal = null; }
  window.STAR_MINER_CONFIG = CONFIG;
  boot();
})();
